name: Test

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
      - run: uv run pytest
  required-status-check:
    name: test.required-status-check
    needs:
      - test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Use this job as the required status check of this workflow"
      - name: Check that all jobs were successful
        env:
          RESULTS: ${{ toJSON(needs) }}
        run: |
          echo "$RESULTS" | jq --exit-status 'all(.result == "success")' || exit 1
