name: Test

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - run: uv run pytest
  required-status-check:
    name: test.required-status-check
    needs:
      - test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Use this job as the required status check of this workflow"
      - name: Check that all jobs were successful
        env:
          RESULTS: ${{ toJSON(needs) }}
        run: |
          echo "$RESULTS" | jq --exit-status 'all(.result == "success")' || exit 1
